- floor: 8
  altitude: 80.4
  map_name: '/eng2/8f'
- floor: 7
  altitude: 76.35
  map_name: '/eng2/7f'
- floor: 6
  altitude: 72.3
  map_name: '/eng2/6f'
- floor: 5
  altitude: 67.2
  map_name: '/eng2/5f'
- floor: 4
  altitude: 63.2
  map_name: '/eng2/4f'
- floor: 3
  altitude: 59.1
  map_name: '/eng2/3f'
- floor: 2
  altitude: 54.8
  map_name: '/eng2/2f'
- floor: 1
  altitude: 49.8
  map_name: '/eng2/1f'
